env:
  browser: true
  es2021: true
  jest/globals: true
extends: 
 - eslint:recommended
 - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules: {}
